kind: "EntandoApp"
apiVersion: "entando.org/v1"
metadata:
  annotations: {}
  labels: {}
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  dbms: {{ .Values.app.dbms }}
  replicas: {{ .Values.app.replicaCount }}
  customServerImage: "{{ .Values.app.repository }}:{{ .Values.app.tag }}"
  ingressPath: /my-sample-app
