kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Release.Name }}-composite-app"
  namespace: {{ .Release.Namespace}}
entandoStatus:
  serverStatuses: {}
  entandoDeploymentPhase: "requested"
spec:
  components:
    - kind: "EntandoKeycloakServer"
      metadata:
        name: "{{ .Release.Name }}-kc"
      spec:
        dbms: none
        isDefault: true
        replicas: 1
    - kind: "EntandoClusterInfrastructure"
      metadata:
        name: "{{ .Release.Name }}-eci"
      spec:
        dbms: postgresql
        replicas: 1
        isDefault: true
